### ISSUE TITLE
Wrong result in iPhone

### ISSUE THREAD

**Issue by daneshka** [featurist/browser-pdf-support#1]
We used this library and it works well everywhere.
Only on my iPhone (both Safari and Chrome) it returns false (pdf not supported) but in practice, I can preview the pdf files there.

**Comment by refractalize** [comment]
Thanks for reporting @daneshka, does #2 fix your problem?

**Comment by daneshka** [comment]
Wow, Thanks for your quick pull request.
But unfortunately, I have still the same issue. On iPhone, it returns null but actually, it can preview pdf files.
For now, I just check the OS by [bowser](https://www.npmjs.com/package/bowser) library if it's IOS and it's Chrome or Safari, I preview the pdf. (probably not the best solution because I don't check OS and Browser version)

**Comment by refractalize** [comment]
@daneshka I've released this code now, in v0.2.0, can you try again?
